// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzvZz0xWbkV_EulXiVrV7x-iBGd8rO864',
    appId: '1:592173740452:web:6f95776b2f16e3b1349131',
    messagingSenderId: '592173740452',
    projectId: 'sns-like-42bc2',
    authDomain: 'sns-like-42bc2.firebaseapp.com',
    storageBucket: 'sns-like-42bc2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-YasfM7P6_O1PNQ_9WBkn_RA6DNkdPLA',
    appId: '1:592173740452:android:c9d2e8eea8b39b6a349131',
    messagingSenderId: '592173740452',
    projectId: 'sns-like-42bc2',
    storageBucket: 'sns-like-42bc2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjif72GSj1vIA2GTC5Vh3ZVfa1V5BaRtM',
    appId: '1:592173740452:ios:77a92ba7661b813e349131',
    messagingSenderId: '592173740452',
    projectId: 'sns-like-42bc2',
    storageBucket: 'sns-like-42bc2.appspot.com',
    iosClientId: '592173740452-9visegnnbi5i867io70kml23tqnfup6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.likeSns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjif72GSj1vIA2GTC5Vh3ZVfa1V5BaRtM',
    appId: '1:592173740452:ios:77a92ba7661b813e349131',
    messagingSenderId: '592173740452',
    projectId: 'sns-like-42bc2',
    storageBucket: 'sns-like-42bc2.appspot.com',
    iosClientId: '592173740452-9visegnnbi5i867io70kml23tqnfup6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.likeSns',
  );
}
